# Generated by Django 4.1.5 on 2023-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="описание задачи", max_length=140)),
                (
                    "time_begin",
                    models.DateTimeField(
                        auto_now_add=True, help_text="время создания задачи"
                    ),
                ),
                (
                    "time_end",
                    models.DateTimeField(
                        blank=True,
                        default=False,
                        help_text="время завершения задачи",
                        null=True,
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, help_text="выполнена ли задача"),
                ),
            ],
        ),
    ]
