# Generated by Django 4.1.5 on 2023-03-05 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="author",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор задачи",
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="author",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор задачи",
            ),
        ),
    ]
