# Generated by Django 4.1.5 on 2023-02-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0002_category_todolist_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="cat",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                to="todolist.category",
                verbose_name="Категория",
            ),
        ),
    ]
