# Generated by Django 4.1.5 on 2023-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="is_completed",
            field=models.BooleanField(
                default=False, verbose_name="выполнена ли задача"
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="name",
            field=models.CharField(max_length=140, verbose_name="описание задачи"),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="time_begin",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="время создания задачи"
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="time_end",
            field=models.DateTimeField(
                blank=True,
                default=False,
                null=True,
                verbose_name="время завершения задачи",
            ),
        ),
    ]
